apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-namespace
  labels:
    app: test-pod
    egress-gateway: "enabled"  # Added label
spec:
  containers:
    - name: test-container
      image: arunvelsriram/utils
      command:
        - "/bin/bash"
        - "-c"
        - "while true; do sleep 3600; done"
      tty: true
      stdin: true
