- name: Make sure slurm-worker is in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '\s{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
  loop: "{{ groups['slurm_worker'] }}"
