- name: Enable Slurm services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - slurmdbd
    - slurmctld
  when: (slurm_packages.changed) or
        (slurm_common_packages.changed)
