- name: Make sure slurm-master is in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '\sslurm-master$'
    line: "{{ hostvars['slurm-master']['ansible_default_ipv4']['address'] }} slurm-master"

- name: Make sure slurm-worker is in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '\s{{ item }}$'
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
  loop: "{{ groups['slurm_worker'] }}"
  when: item != inventory_hostname
