kind: PersistentVolume
apiVersion: v1
metadata:
  name: store-persistent-volume
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/filestore/pvc"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: store-persistent-volume-claim
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi