- name: Clone the repository PMIX
  get_url:
    url: https://github.com/openpmix/openpmix/releases/download/v{{ PMIX_VERSION }}/pmix-{{ PMIX_VERSION }}.tar.gz
    dest: /usr/src/pmix-{{ PMIX_VERSION }}.tar.gz
  register: pmix_repo

- name: Uncompress PMIX
  unarchive:
    src: /usr/src/pmix-{{ PMIX_VERSION }}.tar.gz
    dest: /usr/src/
  when: pmix_repo.changed
  register: pmix_file

- name: Configure PMIX
  shell: ./configure
  args:
    chdir: "/usr/src/pmix-{{ PMIX_VERSION }}"
  when: pmix_file.changed

- name: Make and install PMIX
  make:
    target: install
    jobs: "{{ ansible_processor_cores }}"
    chdir: "/usr/src/pmix-{{ PMIX_VERSION }}"
  when: pmix_file.changed
